cmake_policy(VERSION 3.28.0)
include_guard(GLOBAL)
if(NOT DEFINED __INCLUDED_CYY_CMAKE_MODULES)
  set(__INCLUDED_CYY_CMAKE_MODULES
      TRUE
      CACHE INTERNAL "INCLUDED_CYY_CMAKE_MODULES_MARK")
  list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/module)
endif()
include(${CMAKE_CURRENT_LIST_DIR}/build_type.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/basic_compiling_option.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/fix_compiler_bug.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/fuzzing.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/linker.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/optimization.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/static_code_analysis.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/refactor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/code_coverage.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/profiling.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/documentation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/security.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/code_format.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/eink.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/build_cache.cmake)
