cmake_policy(VERSION 3.17.0)
include(CTest)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/module)
include(${CMAKE_CURRENT_LIST_DIR}/build_type.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/basic_compiling_option.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/test.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/fuzzing.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/linker.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/optimization.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/static_code_analysis.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/refactor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/windows.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/code_coverage.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/profiling.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/documentation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/security.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/code_format.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/eink.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/build_cache.cmake)
