include_guard(GLOBAL)
cmake_policy(VERSION 3.11)
get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(NOT isMultiConfig) 
  if(NOT CMAKE_BUILD_TYPE) 
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE)
  endif()
endif()

function(add_custom_build_type build_type)
  if(isMultiConfig) 
    if(NOT ${build_type} IN_LIST CMAKE_CONFIGURATION_TYPES) 
      list(APPEND CMAKE_CONFIGURATION_TYPES ${build_type})
    endif() 
  else()
    get_property(build_type_strings CACHE CMAKE_BUILD_TYPE PROPERTY build_type_strings)
    if(NOT ${build_type} IN_LIST build_type_strings)
      list(APPEND build_type_strings ${build_type})
    endif()
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "${build_type_strings}")
  endif()
endfunction()
