option(ENABLE_CODE_COVERAGE "Enable code coverage" OFF)

if(NOT ENABLE_CODE_COVERAGE)
  return()
endif()

SET(ENABLE_GNU_CODE_COVERAGE FALSE)
SET(ENABLE_LLVM_CODE_COVERAGE FALSE)

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fprofile-instr-generate -fcoverage-mapping")
  SET(ENABLE_LLVM_CODE_COVERAGE TRUE)
ELSEIF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} --coverage")
  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS} --coverage")
  SET(ENABLE_GNU_CODE_COVERAGE TRUE)
endif()
