IF(CMAKE_BUILD_TYPE MATCHES DEBUG)
  add_definitions(_GLIBCXX_DEBUG _GLIBCXX_SANITIZE_VECTOR)
endif()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /sdl")
ENDIF()
