include_guard(GLOBAL)
set(CMAKE_LINK_WHAT_YOU_USE TRUE)
if(MSVC)
  return()
endif()
get_property(languages GLOBAL PROPERTY ENABLED_LANGUAGES)
if(CXX IN_LIST languages)
  find_package(mold QUIET)
  if(TARGET mold::mold)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      add_link_options($<$<COMPILE_LANGUAGE:CXX>:-fuse-ld=mold)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION
                                                    VERSION_GREATER 12.0)
      add_link_options($<$<COMPILE_LANGUAGE:CXX>:-fuse-ld=mold)
    endif()
  endif()
endif()
