include_guard(GLOBAL)
option(WITH_IPO "Build code with ipo" OFF)
if(NOT WITH_IPO)
  return()
endif()

include(CheckIPOSupported)
get_property(languages GLOBAL PROPERTY ENABLED_LANGUAGES)
set(c_or_cxx)
if("C" IN_LIST languages)
  list(APPEND c_or_cxx "C")
endif()
if("CXX" IN_LIST languages)
  list(APPEND c_or_cxx "CXX")
endif()
check_ipo_supported(RESULT result OUTPUT output LANGUAGES ${c_or_cxx})
if(result)
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)
else()
  message(FATAL_ERROR "IPO is not supported: ${output}")
endif()
