ENABLE_TESTING()

if(NOT TARGET profiling)
  ADD_CUSTOM_TARGET(profiling COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure -C $<CONFIGURATION>)
endif()

function(profiling_prog)
  set(oneValueArgs TARGET)
  cmake_parse_arguments(this "" "${oneValueArgs}" "ARGS" ${ARGN})
  if("${this_TARGET}" STREQUAL "")
    message(FATAL_ERROR "no target specified")
    return()
  endif()
  separate_arguments(this_ARGS)
  IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_compile_options(${this_TARGET} PRIVATE "-pg")
    set_target_properties(${this_TARGET} PROPERTIES LINK_FLAGS "-pg")
  endif()
  set(name ${this_TARGET})
  add_test(NAME "profiling_${name}" WORKING_DIRECTORY $<TARGET_FILE_DIR:${this_TARGET}> COMMAND $<TARGET_FILE:${this_TARGET}> ${this_ARGS})
  add_dependencies(profiling ${this_TARGET})
endfunction()
