include_guard(GLOBAL)
option(WITH_SECURITY_OPTIONS "Add compiling security options" OFF)
if(NOT WITH_SECURITY_OPTIONS)
  return()
endif()

foreach(lang IN LISTS languages)
  if(CMAKE_${lang}_COMPILER_ID STREQUAL "MSVC")
    set(CMAKE_${lang}_FLAGS "${CMAKE_${lang}_FLAGS} /guard:cf")
    foreach(targettype IN ITEMS EXE SHARED STATIC MODULE)
      set(CMAKE_${targettype}_LINKER_FLAGS "${CMAKE_${targettype}_LINKER_FLAGS} /guard:cf")
    endforeach()
  endif()
endif()
