include_guard(GLOBAL)
option(WITH_SECURITY_OPTIONS "Add compiling security options" OFF)
if(NOT WITH_SECURITY_OPTIONS)
  return()
endif()

get_property(languages GLOBAL PROPERTY ENABLED_LANGUAGES)
foreach(lang IN LISTS languages)
  if(CMAKE_${lang}_COMPILER_ID STREQUAL "MSVC")
    set(CMAKE_${lang}_FLAGS "${CMAKE_${lang}_FLAGS} /guard:cf")
  endif()
endforeach()
